server:
  port : 8080

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    spring.thyemleaf.content-type: text/html
    enabled: true
    encoding: UTF-8

logging:
  level:
      - ".=debug"